apiVersion: v2
name: argo-rollouts-config-mapper
description: A Kubernetes mutating admission webhook that dynamically rewrites ConfigMap and Secret references in Pod specs during ArgoCD Rollouts preview deployments
type: application
version: 0.1.3
appVersion: "latest"
keywords:
  - kubernetes
  - admission-webhook
  - argo-rollouts
  - configmap
  - secret
  - preview
home: https://github.com/lsdopen/argo-rollouts-config-mapper
sources:
  - https://github.com/lsdopen/argo-rollouts-config-mapper
maintainers:
  - name: Seagyn Davis
    email: seagyn@lsdopen.io
